export { About } from './src/main/ets/pages/About';

export { CollectedUserInfo } from './src/main/ets/pages/CollectedUserInfo';

export { Privacy } from './src/main/ets/pages/Privacy';

export { Settings } from './src/main/ets/pages/Settings';

export { SharedUserInfo } from './src/main/ets/pages/SharedUserInfo';

export { SyncData } from './src/main/ets/pages/SyncData'

export { TOS } from './src/main/ets/pages/TOS';