export { AboutPage } from './src/main/ets/pages/AboutPage';

export { CollectedUserInfoPage } from './src/main/ets/pages/CollectedUserInfoPage';

export { PrivacyPage } from './src/main/ets/pages/PrivacyPage';

export { SettingPage } from './src/main/ets/pages/SettingPage';

export { SharedUserInfoPage } from './src/main/ets/pages/SharedUserInfoPage';

export { SyncDataPage } from './src/main/ets/pages/SyncDataPage'

export { TosPage } from './src/main/ets/pages/TosPage';