export class  Icon {
  static readonly ic_bookmark: Resource = $r('app.media.ic_bookmark');
  static readonly ic_bookmark_border: Resource = $r('app.media.ic_bookmark_border');
  static readonly ic_public_cloud_download: Resource =  $r('app.media.ic_public_cloud_download');
  static readonly ic_public_delete: Resource =  $r('app.media.ic_public_delete');
  static readonly ic_public_download: Resource =  $r('app.media.ic_public_download');
  static readonly ic_public_refresh: Resource =  $r('app.media.ic_public_refresh');
  static readonly ic_public_search: Resource =  $r('app.media.ic_public_search');
  static readonly ic_public_settings: Resource =  $r('app.media.ic_public_settings');
}