export class Icon {
  static readonly app_icon: Resource = $r('app.media.foreground')
  static readonly ic_bookmark: Resource = $r('app.media.ic_bookmark');
  static readonly ic_bookmark_border: Resource = $r('app.media.ic_bookmark_border');
  static readonly ic_link: Resource = $r('app.media.ic_link');
  static readonly ic_public_cloud_download: Resource = $r('app.media.ic_public_cloud_download');
  static readonly ic_public_delete: Resource = $r('app.media.ic_public_delete');
  static readonly ic_public_download: Resource = $r('app.media.ic_public_download');
  static readonly ic_public_folder: Resource = $r('app.media.ic_public_folder');
  static readonly ic_public_picture: Resource = $r('app.media.ic_public_picture');
  static readonly ic_public_refresh: Resource = $r('app.media.ic_public_refresh');
  static readonly ic_public_search: Resource = $r('app.media.ic_public_search');
  static readonly ic_public_settings: Resource = $r('app.media.ic_public_settings');
  static readonly ic_public_text_black: Resource = $r('app.media.ic_public_text_black');
  static readonly ic_public_text_white: Resource = $r('app.media.ic_public_text_white');
  static readonly ic_public_todo: Resource = $r('app.media.ic_public_todo');
  static readonly ic_public_todo_filled: Resource = $r('app.media.ic_public_todo_filled');
  static readonly ic_read_more: Resource = $r('app.media.ic_read_more');
}