export class NetworkConst {
  static readonly HTTP_CODE_200: number = 200;
  static readonly HTTP_CONNECT_TIMEOUT: number = 600000; //单位：ms
  static readonly HTTP_READ_TIMEOUT: number = 600000;
  static readonly PRIVACY_LINK: string = 'https://jingmo.ruaruan.com/docs/privacy-policy/';
  static readonly TOS_LINK: string = 'https://jingmo.ruaruan.com/docs/user-agreement/';
  static readonly BASE_URL1: string = "https://p1-cdn.jingmo.ruaruan.com/api/";
  static readonly BASE_URL2: string = "https://p2-cdn.jingmo.ruaruan.com/api/";
  static readonly BASE_URL3: string = "https://p3-cdn.jingmo.ruaruan.com/api/";
  static readonly DATASET: string = "dataset_v2";
  static readonly CHINA_WORLDCULTUREHERITAGE: string = "china_worldcultureheritage";
  static readonly CHINESE_ANTITHETICALCOUPLET: string = "chinese_antitheticalcouplet";
  static readonly CHINESE_CHARACTER: string = "chinese_character";
  static readonly CHINESE_EXPRESSION: string = "chinese_expression";
  static readonly CHINESE_IDIOM: string = "chinese_idiom";
  static readonly CHINESE_KNOWLEDGE: string = "chinese_knowledge";
  static readonly CHINESE_LYRIC: string = "chinese_lyric";
  static readonly CHINESE_MODERNPOETRY: string = "chinese_modernpoetry";
  static readonly CHINESE_PROVERB: string = "chinese_proverb";
  static readonly CHINESE_QUOTE: string = "chinese_quote";
  static readonly CHINESE_RIDDLE: string = "chinese_riddle";
  static readonly CHINESE_TONGUETWISTER: string = "chinese_tonguetwister";
  static readonly CHINESE_WISECRACK: string = "chinese_wisecrack";
  static readonly CLASSICALLITERATURE_CLASSICPOEM: string = "classicalliterature_classicpoem";
  static readonly CLASSICALLITERATURE_PEOPLE: string = "classicalliterature_people";
  static readonly CLASSICALLITERATURE_SENTENCE: string = "classicalliterature_sentence";
  static readonly CLASSICALLITERATURE_WRITING: string = "classicalliterature_writing";
}