export class NetworkConst {
  static readonly HTTP_CODE_200: number = 200
  static readonly HTTP_READ_TIMEOUT: number = 10000
  static readonly PRIVACY_LINK: string = 'https://jingmo.ruaruan.com/docs/privacy-policy/'
  static readonly TOS_LINK: string = 'https://jingmo.ruaruan.com/docs/user-agreement/'
  static readonly BASE_URL1: string = "https://p1-cdn.jingmo.ruaruan.com/api/"
  static readonly BASE_URL2: string = "https://p2-cdn.jingmo.ruaruan.com/api/"
  static readonly BASE_URL3: string = "https://p3-cdn.jingmo.ruaruan.com/api/"
  static readonly DATASET: string = "dataset_v2"
}